[package]
name = "wms"
version = "0.1.0"
description = "WMS 桌面客户端"
license = "ISC"
edition = "2021"
rust-version = "1.77.2"

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.6.3", features = [] }

[dependencies]
tauri = { version = "2.11.6", features = [] }
